nnoremap <silent> <F8> :TagbarToggle<CR>
let g:tagbar_autopreview = 1
let g:no_status_line = 1
let g:tagbar_autofocus = 1
let g:tagbar_zoomwidth = 0
let g:tagbar_show_data_type = 1
let g:tagbar_show_linenumbers = 1
let g:tagbar_show_tag_count = 1
let g:tagbar_foldlevel = 2
let g:tagbar_autoshowtag = 1
let g:tagbar_highlight_follow_insert = 1
let g:tagbar_highlight_method = 'nearest'
highlight TagbarHighlight guifg=Green ctermfg=Green
highlight TagbarTagLineN guifg=Green ctermfg=Green